docker:
  host: "***" # Already has defaults based on your OS
  username: "***"
  authorization: "***"
artifactory:
  url: "***"
  repository: "***"
cloudProvider:
  type: "openshift"
  url: "***"
  namespace: "***"
  authorizationToken: "***" # get it from openshift (Bearer token)